//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudijeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public short Indeks { get; set; }
        public short Upisan { get; set; }
        public string Imes { get; set; }
        public string Mesto { get; set; }
        public Nullable<System.DateTime> Datr { get; set; }
        public Nullable<short> Ssmer { get; set; }
    }
}
